ListModel: port to Vala
elementary/files pull request #1547
Opened 2021-01-05 12:16 UTC by tintou

This is a simple rebase of https://github.com/elementary/files/pull/373
The same issues remains.

2021-01-07 16:45 UTC, jeremypw requested changes
Just a couple of very minor code comments for now.  

Do we need/want to support our own (re)implementation of TreeModel?  Is this faster/more efficient than using the Gtk implementation?

2021-01-07 16:45 UTC, jeremypw commented on libcore/ListModel.vala
> +/* Copyright (c) 2018 elementary LLC (https://elementary.io)
Need to update the date.

2021-01-07 16:45 UTC, jeremypw commented on libcore/ListModel.vala
> +        public static ColumnID from_string (string colid) {
No reason to use a weird identifier like `colid` - could use `column_id`

2021-01-07 17:02 UTC, tintou commented
@jeremypw You're more familiar with the Files codebase than I am, but if we can use the Gtk model, then we should probably do it. If there is any performance issue I'm pretty confident that it shouldn't be the case anymore when we switch to GTK4

2021-01-07 17:14 UTC, jeremypw commented
Well, comparing the old experimental PR I did using Gtk.TreeStore (#824), you seem to have saved almost as many lines of code with this PR. So on reflection, I am not sure whether it worth the effort and risk of regression/performance issues trying to switch.  So I would be happy to merge this once the issues with the expanders and keyboard shortcuts are fixed.

2021-01-12 18:56 UTC, jeremypw requested changes
See inline

2021-01-12 18:56 UTC, jeremypw commented on libcore/ListModel.vala
> +            file_entry.files = file_entry_files;
This does not work.  The new `Sequence<FileEntry?>` gets freed as soon as the clause exits.  This is why no expanders appear on folders in ListView. However the obvious port of the C `file_entry.files = new Sequence<FileEntry?>()` gives an error both when file_entry.files is owned (duplicating a sequence) or unowned (assigning owned to unowned).  Not sure what the solution is to this.  Is Vala behaving correctly here?  May need to use a different structure for FileEntry and/or Sequence

2021-04-18 17:38 UTC, jeremypw commented
@tintou I suggest you close this one and propose the `tintou/listmodel-simple` branch.

2021-04-18 21:07 UTC, closed without merging