ProgressInfoWidget: Use tabular numbers in file transfer dialog
elementary/files pull request #1612
Opened 2021-03-03 12:47 UTC by bluesabre

This branch updates both the status and details labels with tabular numbers. Please let me know if I need to make any other changes. Thanks!

Closes #1567

2021-03-03 18:19 UTC, jeremypw requested changes
Thanks for your first contribution to Files! :grinning: 

I think the attribute should be "font-features", not "font_features"

2021-03-03 18:19 UTC, jeremypw commented on src/View/Widgets/ProgressInfoWidget.vala
> +            Markup.printf_escaped ("<span font_features='tnum'>%s</span>", info.status)
Shouldn't this be `<span font-features='tnum' ....`?  It doesn't seem to work otherwise.

2021-03-03 18:19 UTC, jeremypw commented on src/View/Widgets/ProgressInfoWidget.vala
> +            Markup.printf_escaped ("<span size='small' font_features='tnum'>%s</span>", info.details)
See comment above

2021-03-03 23:13 UTC, bluesabre commented
Thanks for the review! From my testing, it seems like either dash or underscore was working, and I based it on https://github.com/elementary/wingpanel-indicator-datetime/pull/246/files

Since they both work, I went ahead and swapped the code over to dashes instead. Please let me know if I need to adjust anything else.

2021-03-04 10:18 UTC, jeremypw commented
Strange - when I tested it there still seemed to be some movement unless I changed the underscore to hyphen.  I think hyphens are more usual for quoted properties, attributes & signal names and in some other circumstances (e.g. property bindings) mandatory.  Anyway, thanks for changing it - I will approve now.

2021-03-04 10:18 UTC, jeremypw approved these changes

2021-03-08 22:50 UTC, cassidyjames approved these changes

2021-03-08 22:55 UTC, merged