Adds missing tooltip to the cancel button in file transfer widget
elementary/files pull request #1743
Opened 2021-06-28 00:33 UTC by Eldhrimer

Fixes #1740 

PS: This is my first PR ever, so excited.

2021-06-28 00:50 UTC, Eldhrimer commented
Just a note, I was thinking of writing "Cancel file transfer" in the tooltip, but I don't fully understand how translatable strings work, so instead I used the "Cancel" string that I saw it was already in used in .po files. I like the former because it's more explanatory, though

2021-06-28 08:05 UTC, jeremypw commented
Congratulations on your first PR! First of many hopefully.  

You do not need worry too much about translatable strings except to make sure that they are easily translated into any language (using comments to translators if necessary).  You usually only need put the desired string inside the `_()` function. The rest happens automatically.

 "Cancel file transfer" is not always appropriate as the progress widget could appear during any file operation that takes longer than a couple of seconds.  As the button is closely associated with the status and details labels I am not sure that added information in the tooltip is strictly necessary.

2021-06-28 08:12 UTC, jeremypw commented
@Eldhrimer You have a lint error that needs fixing - whitespace at the end of a line.  Make sure that your editor is set to strip trailing whitespace when saving a code file.  You can run the lint check locally before committing by installing the `io.elementary.vala-lint` package and running `io.elementary.vala-lint -d <source-root>` in a terminal.

2021-06-28 10:20 UTC, tintou commented on src/View/Widgets/ProgressInfoWidget.vala
> +        button.set_tooltip_text (_("Cancel"));
Prefer setting the property directly for better readability
```suggestion
        button.tooltip_text = _("Cancel");
```

2021-06-28 12:41 UTC, Eldhrimer commented
Thanks for your responses!

@jeremypw I understand better about transalatable strings, it's better to stick to "Cancel" then. And I have enabled the plugin for stripping trailing whitespaces in Code!

@tintou I have commited with your modifications, I'll take note of this preferred style for future contributions.

Thanks!

2021-06-29 16:31 UTC, danrabbit requested changes
Hey thanks for making this pull request! My only suggestion would be to set this property where the button is initialized. This is part of the latest version of our code style guide which you can find here: https://docs.elementary.io/develop/writing-apps/code-style#initialize-objects-with-properites

In this case, that would mean modifying the bit at line 62 from this:

```
        var button = new Gtk.Button.from_icon_name ("process-stop-symbolic", Gtk.IconSize.BUTTON);
        button.get_style_context ().add_class (Gtk.STYLE_CLASS_FLAT);
```

to this
```
        var button = new Gtk.Button.from_icon_name ("process-stop-symbolic", Gtk.IconSize.BUTTON) {
            tooltip_text = _("Cancel")
        };
        button.get_style_context ().add_class (Gtk.STYLE_CLASS_FLAT);
```

2021-06-29 17:01 UTC, Eldhrimer commented
I pushed a new commit with changes requested by @danrabbit

2021-06-29 17:02 UTC, danrabbit approved these changes
Fantastic! Thanks for your contribution and solving this issue :tada:

2021-06-29 17:03 UTC, merged