Bulk renamer plugin
elementary/files pull request #1974
Opened 2022-01-07 17:56 UTC by jeremypw

Fixes #1040 

Functional but needs UX of dialog sorting out.  Suggestions welcome.

2022-01-11 23:37 UTC, danrabbit requested changes
Wow this is a lot! First thing, instead of a separate plugin/menuitem, this should probably just be the behavior for the `Rename` menuitem when multiple files are selected

I kind of feel like this is probably overwhelming for most people to the point of not longer being useful. Perhaps we should scope down here to just simple renaming schemes and leave some of the more advanced stuff for specialized apps if you really have a wild use case? I'd guess the vast majority of bulk renaming operations would be to suffix with either numbers or a date, but probably not multiple combinations of prefixes, suffixes, and dates.

The GNOME approach here is also interesting. It uses a single entry where you can add items from a menu to make a regex-like template:

![nautilus-batch-rename](https://user-images.githubusercontent.com/7277719/149037866-9afeba27-dd88-45ef-9085-65e56d18ace2.png)

This seems like it would allow for really flexible renaming while keeping things simple for someone to specify a format like `[Original file name]-[1, 2, 3]`.

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/RenamerDialog.vala
> +public class Files.RenamerDialog : Gtk.Dialog {
Using Granite.Dialog here would save some styling work

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/RenamerDialog.vala
> +        deletable = true;
Dialogs shouldn't have close window controls since it's ambiguous what happens when the window is closed. 
```suggestion
```

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/RenamerDialog.vala
> +        });
Probably should find the actual cause of this, this seems pretty janky

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/RenamerDialog.vala
> +                        response (Gtk.ResponseType.APPLY);
This definitely isn't the right way to do this. the "Rename" button should have `has_default = true` and entry widgets in the dialog should have `activates_default = true`

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/BulkRenamer.vala
> +        base_name_label.get_style_context ().add_class (Granite.STYLE_CLASS_H2_LABEL);
Making these header labels this big seems pretty excessive

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/BulkRenamer.vala
> +            placeholder_text = _("Enter naming scheme"),
Placeholder text should be an example of valid text for this entry. Descriptions of entries should be labels outside the entry. I'm not sure what good example text here would be, so we should probably remove this

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/BulkRenamer.vala
> +            max_width_chars = 64,
Is there a reason for restricting the character limit here?

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/BulkRenamer.vala
> +            hexpand = false,
expand is `false` by default, so we don't need to specify it
```suggestion
```

2022-01-11 23:37 UTC, danrabbit commented on plugins/bulk-renamer/BulkRenamer.vala
> +        sort_type_grid.add (sort_type_label);
This seems kind of excessive. Do we really need sort controls here?

2022-01-12 10:43 UTC, jeremypw commented
Thanks for the review.  This was originally written as a separate app but I never got round to submitting it to AppCenter as I had difficulty coming up with a suitable icon/name.  I submitted it here in response to renewed interest in the related issue.

I'll have a think about simplifying the UX so only the most commonly used options appear initially and perhaps hide less used options under an "Advanced..." button or something.  The screenshot does show more modifiers than most people would use just to illustrate that you can chain an arbitrary number of them.  The dialog does need to be made smaller.

Regarding having only one option "Rename",  I have also submitted an alternative way the existing option could handle a multiple selection, i.e. by sequentially renaming them arbitrarily (which this PR cannot do at present).  I guess in most cases where a user wants to rename multiple files it is in order to apply some pattern though.

2022-01-12 10:49 UTC, jeremypw commented
The code is quite old so definitely needs updating to best practices!

2022-01-12 11:10 UTC, jeremypw commented
I can drop the sorting of the original files and have it follow the current sort order of the view.

2022-01-28 13:17 UTC, jeremypw commented
Closed in favour of #1999, which is not a plugin and has a simpler interface.

2022-01-28 13:17 UTC, closed without merging