Reset pathbar on lost focus
elementary/files pull request #2090
Opened 2022-10-19 10:31 UTC by darthgelum

Fixes #2068
Based on solution by @jeremypw #2069 but checks `Gdk.WindowState.Focus`

Works on hiding by button and clicking icon

2022-10-21 08:44 UTC, jeremypw commented
@darthgelum Would you update this PR please?  Thanks.

2022-11-05 19:39 UTC, darthgelum commented
Sorry, will update in a  week. Thanks!

2022-12-09 11:20 UTC, jeremypw requested changes

2022-12-09 11:20 UTC, jeremypw commented on libcore/Widgets/BasicBreadcrumbsEntry.vala
> +                     (top_level.get_window ().get_state () & Gdk.WindowState.FOCUSED) > 0) ||
There are unmatched brackets here so this does not compile.

2022-12-09 11:25 UTC, jeremypw commented
When the bracket issue is fixed this fixes the linked issue and no regressions were found.

2023-06-29 18:34 UTC, jeremypw commented
To retarget on Gtk4 version

2023-06-29 18:34 UTC, closed without merging