Move HeaderBar into Window and create AppMenu class
elementary/files pull request #2233
Opened 2023-07-01 00:06 UTC by danirabbit

This can be rebase merged if desired

Since we can't subclass HeaderBar in Gtk4, this moves the AppMenu into its own class and then puts the rest of HeaderBar directly into the main window. From what I can tell this actually removes some pointless lasagna so :tada:

2023-07-02 09:52 UTC, jeremypw commented
@danirabbit Please fix conflicts.

2023-07-04 09:29 UTC, jeremypw requested changes
This seems to introduce some regressions:
1. `<Ctrl>F` shortcut no longer triggers search mode
2. Pressing `<Ctrl>F` after starting rubberband select makes rubberbanding persist until `Esc` is pressed.
3. `<Ctrl><Shift>N` creates new folder but also sends a notification and interferes with rubberbanding.

In fact many/most keyboard shortcuts interfere with rubberbanding now.

2023-07-11 20:54 UTC, danirabbit commented
@jeremypw I can't confirm an issue with triggering search mode. Can you try that again?


unless I'm misunderstanding, I can reproduce the rubberbanding issues in main as well. This seems to be related to these lines in main:

```
            top_menu.focus_in_event.connect (() => {
                current_tab.is_frozen = true;
                return true;
            });
            top_menu.focus_out_event.connect (() => {
                current_tab.is_frozen = false;
                return true;
            });
```

2023-07-12 15:56 UTC, jeremypw commented
I can now confirm the rubberband issue in master as well - sorry about that. I'll raise an issue, though whether its serious enough to fix in Gtk3 is questionable. 

I have still several issues with this branch however - I'll investigate further before reporting this time.

2023-07-12 19:06 UTC, jeremypw commented
Issues noticed so far:
* Browser buttons do not react to click but *do* react to long press
* Clicking on a folder does not navigate
* Pressing `<Ctrl>F` has no apparent effect but ..
* After pressing `<Ctrl>F` and *then* starting a rubberband selection, the rubberbanding does not end on releasing the primary button.   This is different from in main where the issue only occurs if the shortcut is pressed *while* rubberbanding.

It is not obvious from the diff what the problem is but it is something to do with focus and/or event capturing.

2023-07-12 19:10 UTC, jeremypw commented
Could be something to do with the timing/order of events changed by collapsing chained signals/signal handlers into one. May need to use `connect_after`??

2023-07-12 19:16 UTC, jeremypw commented on src/View/Window.vala
> +            return focus_in_event (event);
Should be `header_bar.focus_in_event (event)`

2023-07-12 19:16 UTC, jeremypw commented on src/View/Window.vala
> +            return focus_out_event (event);
Should be `header_bar.focus_out_event (event)`

2023-07-12 19:18 UTC, jeremypw commented
The above changes to the focus event handlers seems to fix the problems!

2023-07-13 19:05 UTC, jeremypw commented
Hmm, it seems the browser button problem is still not fixed - the others are.  I'll have another look.

2023-07-13 19:06 UTC, jeremypw commented
@danirabbit  I don't think you have connected the browser buttons' `activated` signal?

2023-07-13 19:20 UTC, danirabbit commented
@jeremypw oops you're right. Somehow I removed the connections in one of these conflict resolves. I think it's fixed now

2023-07-14 09:16 UTC, jeremypw approved these changes
Everything seems to work now.

2023-07-14 09:16 UTC, merged