Sidebar Gtk4 Prep
elementary/files pull request #2287
Opened 2023-08-15 18:33 UTC by danirabbit

Starting over based on changes from #2082

Still has a ton of criticals and warnings

2023-08-15 19:56 UTC, danirabbit commented on libcore/Interfaces/SidebarListInterface.vala
> +            list_box.remove (child);
I don't fully understand this, but if we call `remove` before `destroy` we get a whole bunch of errors about how this isn't a widget or isn't a container and there's unclassed pointers etc etc. But if we destroy and then remove there's nothing :woman_shrugging:

2023-08-16 09:00 UTC, jeremypw commented on libcore/Interfaces/SidebarListInterface.vala
> +            list_box.remove (child);
It is because you changed `Gtk.Widget` to  `unowned var `.  If you remove `child` from the listbox there is nothing referencing it so you cannot safely refer to it again.  Using `Gtk.Widget` adds another reference so the order of subsequent actions does not matter.

2023-08-16 09:02 UTC, jeremypw requested changes
You can reduce the diff by reverting changes to the `clear ()` function.  Otherwise everything seems to work as before.

2023-08-17 16:48 UTC, danirabbit commented on libcore/Interfaces/SidebarListInterface.vala
> +            list_box.remove (child);
Ah I had no idea that the `var` keyword could have an effect on references. Thanks!

2023-08-23 14:53 UTC, merged